print("Rengel Tamás")
print("2023.12.12.\n")

print ("     @")
print ("     @")
print ("    @@")
print ("    @")
print ("  @@@@@@")
print (" @@ @@ @@")
print (" @   @  @")
print (" @      @")
print (" @@     @")
print ("  @@  @@")
print ("    @@@")
